# Generated by Django 3.2.3 on 2021-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplanner', '0003_auto_20210526_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='telephone_number',
            field=models.IntegerField(),
        ),
    ]
