# Generated by Django 3.2.3 on 2021-05-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medplanner', '0004_alter_surgery_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='medplanner.Tag'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='medplanner.Specialization'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='surgery_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='medplanner.surgery'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='medplanner.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='medplanner.user'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='telephone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
