# Generated by Django 3.2.3 on 2021-06-02 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplanner', '0005_auto_20210530_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
