version: "3.3"
   
services:
  backend:
    build: ./djangoMedPlanner/
    image: sys-src_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoMedPlanner:/django
    ports:
      - "8000:8000"
    depends_on:
      - migration
      
  migration:
      build: ./djangoMedPlanner/
      image: sys-src_backend:latest
      command: sh -c "python manage.py makemigrations && python manage.py migrate"
      volumes:
        - ./djangoMedPlanner:/django

  frontend:
      image: ng:10.0
      build: ./ngMedPlanner/
      container_name: MedPlanner
      working_dir: /angular
      volumes:
        - ./ngMedPlanner/med-planner:/angular
        - ./ngMedPlannner/build.sh
        - ./ngMedPlanner/setup.sh
      ports:
        - "4220:4220"
      command: ng serve --host 0.0.0.0 --port 4220